version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: foodfast
      POSTGRES_USER: foodfast_user
      POSTGRES_PASSWORD: foodfast_pass
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U foodfast_user -d foodfast']
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for Pub/Sub and Caching
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3

  # Main Express Application
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: foodfast
      DB_USER: foodfast_user
      DB_PASSWORD: foodfast_pass
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-here
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - ./uploads:/app/uploads
    command: npm run dev

volumes:
  postgres_data:
  node_modules:
